name: Build Portfolio HTML

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.html'
      - 'references.html'
      - 'projects.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build portfolio HTML
        run: |
          echo "Building portfolio from portfolio.json..."
          node HTML-compile-complete.js portfolio.json
          echo "HTML files generated successfully"

      - name: Commit and push HTML files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html references.html projects.html 2>/dev/null || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            echo "Committing changes..."
            git commit -m "Auto-generate portfolio HTML files"
            git push
          fi
